name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install zip -y

    - name: Zip files
      run: zip blurwarp-global.zip blur_detection_model.tch run.py module.json requirements.txt

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: blurwarp-global.zip
